language: go
go:
- 1.8
script:
- make test
- make distribution
deploy:
  provider: releases
  api_key:
    secure: Lk0CkCDApIi1rTUoeERLhndnwI4ycD6xGq89GYTcT1GK2VT+WyawFGNvxlgavMobTXonm7hZ8AAY9yzIQ7qFWPEY+jU4UWqQ+yoZonUsqsmnNDl2jTh8eZgqpatdqzgUFQ4S0Fd95YzNZD75dixN7UnyNMb+mkNQEDgjd9RZE9xRmqIHNfexHx34WbFwlx26EVGlslShjzzxR4m67O2cWVCcK70Bm9svTcp+tNakBf/gdWx1DKBNjr2p7I/2XrZvAzCjnWhUBQOHNNafWYp2N8lZ99ipZegIAgRw8B31kzrNeKTYmavgWfvqHD4mwM2PnFjLrHi6Trf3Mbs7uLAvulOqoWeOOFVjDAP6crIZ/usk6wt/f2UIJF7hL5fsepJnfiameIwQh9vf1LL7wUymsRWa4/h7Sadj3YVrXEYx9sD1Oy6d4C5vEW3BSARJmzJ3qxk0N+s0rV6qg5DiWWDDSy0xp4L0cwKMZftfhjua8/D9sZnDB0mdsyJos1sj3x61jZDhzXUWGrrsHJ+WORhZMKpaCuPr40FUW6DBtbOHMYPRLrpg1it8fxWhl4j7IuZNuR+BtGHgVFxLkJ9+Bk7NCRq7OFyBkoh/1ssX+yqt+sWH96MR3ZTNhBSxnUAoj7QSfy4ULYRSJRISrfm/lhJahWbFndG9E8xk2O1Y69PTwVs=
  file:
  - release/apimon-linux-amd64.tgz
  - release/apimon-linux-arm64.tgz
  - release/apimon-linux-arm.tgz
  - release/apimon-darwin-amd64.tgz
  - release/apimon-windows-amd64.exe.tgz
  skip_cleanup: true
  on:
    repo: ncarlier/apimon
    tags: true
