output:
  target: http://0.0.0.0:9090/metrics
  format: prometheus
user_agent: "Mozilla/5.0 (X11; Linux x86_64; rv:10.0) Gecko/20100101 Firefox/10.0"
proxy: http://proxy-internet.localnet:3128/
healthcheck:
  interval: 5s
  timeout: 2s
  rules:
    - name: code
      spec: 200-299
monitors:
  - alias: nunux-keeper-api
    disable: true
    url: https://api.nunux.org/keeper/
    unsafe: true
    headers:
      - "X-API-Key: xxx-xxx-xxx"
    healthcheck:
      timeout: 100ms
      rules:
        - name: code
          spec: 200
